export interface ToolbarButton {
  id: string;
  label: string;
  latex: string;
  title?: string;
}

export interface ToolbarGroup {
  id: string;
  name: string;
  buttons: ToolbarButton[];
}

export const TOOLBAR_GROUPS: ToolbarGroup[] = [
  {
    id: 'basic',
    name: 'Basique',
    buttons: [
      { id: 'num-0', label: '0', latex: '0' },
      { id: 'num-1', label: '1', latex: '1' },
      { id: 'num-2', label: '2', latex: '2' },
      { id: 'num-3', label: '3', latex: '3' },
      { id: 'num-4', label: '4', latex: '4' },
      { id: 'num-5', label: '5', latex: '5' },
      { id: 'num-6', label: '6', latex: '6' },
      { id: 'num-7', label: '7', latex: '7' },
      { id: 'num-8', label: '8', latex: '8' },
      { id: 'num-9', label: '9', latex: '9' },

      { id: 'comma', label: ',', latex: ',' },
      { id: 'dot', label: '.', latex: '.' },
      { id: 'plus', label: '+', latex: '+' },
      { id: 'minus', label: '−', latex: '-' },
      { id: 'times', label: '×', latex: '\\times' },
      { id: 'div', label: '÷', latex: '\\div' },
      { id: 'equals', label: '=', latex: '=' },
      { id: 'neq', label: '≠', latex: '\\neq' },
      { id: 'lparen', label: '(', latex: '(' },
      { id: 'rparen', label: ')', latex: ')' },
      { id: 'lbracket', label: '[', latex: '[' },
      { id: 'rbracket', label: ']', latex: ']' },
      { id: 'var-x', label: 'x', latex: 'x' },
      { id: 'var-y', label: 'y', latex: 'y' },
      { id: 'var-z', label: 'z', latex: 'z' },
      { id: 'var-t', label: 't', latex: 't' },
      { id: 'var-n', label: 'n', latex: 'n' },
      { id: 'var-k', label: 'k', latex: 'k' },
      { id: 'power', label: 'xⁿ', latex: '#?^{#?}', title: 'Puissance' },
      { id: 'sqrt', label: '√', latex: '\\sqrt{#?}', title: 'Racine carrée' },
      { id: 'cbrt', label: '∛', latex: '\\sqrt[3]{#?}', title: 'Racine cubique' },
      { id: 'nthroot', label: '√[n]', latex: '\\sqrt[#?]{#?}', title: 'Racine n-ième' },
      { id: 'abs', label: '|x|', latex: '\\left|#?\\right|', title: 'Valeur absolue' },
      { id: 'ceil', label: '⌈x⌉', latex: '\\lceil #? \\rceil', title: 'Plafond' },
      { id: 'floor', label: '⌊x⌋', latex: '\\lfloor #? \\rfloor', title: 'Partie entière' },
      { id: 'fraction', label: 'a/b', latex: '\\frac{#?}{#?}', title: 'Fraction' },
    ],
  },
  {
    id: 'functions',
    name: 'Fonctions',
    buttons: [
      { id: 'sin', label: 'sin', latex: '\\sin(#?)', title: 'sinus' },
      { id: 'cos', label: 'cos', latex: '\\cos(#?)', title: 'cosinus' },
      { id: 'tan', label: 'tan', latex: '\\tan(#?)', title: 'tangente' },
      { id: 'exp', label: 'eˣ', latex: 'e^{#?}', title: 'exponentielle' },
      { id: 'ln', label: 'ln', latex: '\\ln(#?)', title: 'logarithme naturel' },
      { id: 'log', label: 'log', latex: '\\log(#?)', title: 'logarithme' },
      { id: 'log10', label: 'log₁₀', latex: '\\log_{10}(#?)', title: 'logarithme base 10' },
      { id: 'log-base', label: 'logₐ', latex: '\\log_{#?}(#?)', title: 'logarithme en base a' },
      { id: 'arcsin', label: 'arcsin', latex: '\\arcsin(#?)', title: 'arc sinus' },
      { id: 'arccos', label: 'arccos', latex: '\\arccos(#?)', title: 'arc cosinus' },
      { id: 'arctan', label: 'arctan', latex: '\\arctan(#?)', title: 'arc tangente' },
      { id: 'sinh', label: 'sinh', latex: '\\sinh(#?)', title: 'sinus hyperbolique' },
      { id: 'cosh', label: 'cosh', latex: '\\cosh(#?)', title: 'cosinus hyperbolique' },
      { id: 'tanh', label: 'tanh', latex: '\\tanh(#?)', title: 'tangente hyperbolique' },
      { id: 'arcsinh', label: 'arsinh', latex: '\\operatorname{arsinh}(#?)', title: 'arc sinus hyperbolique' },
      { id: 'arccosh', label: 'arcosh', latex: '\\operatorname{arcosh}(#?)', title: 'arc cosinus hyperbolique' },
      { id: 'arctanh', label: 'artanh', latex: '\\operatorname{artanh}(#?)', title: 'arc tangente hyperbolique' },
    ],
  },
  {
    id: 'calculus',
    name: 'Calcul',
    buttons: [
      { id: 'int', label: '∫', latex: '\\int_{#?}^{#?} #? \\,dx', title: 'intégrale' },
      { id: 'int-indef', label: '∫?', latex: '\\int #? \\,dx', title: 'intégrale indéfinie' },
      { id: 'partial', label: '∂', latex: '\\partial', title: 'dérivée partielle' },
      { id: 'sum', label: '∑', latex: '\\sum_{k=#?}^{#?} #?', title: 'somme' },
      { id: 'prod', label: '∏', latex: '\\prod_{k=#?}^{#?} #?', title: 'produit' },
      { id: 'lim', label: 'lim', latex: '\\lim_{#? \\to #?} #?', title: 'limite' },
      { id: 'infty', label: '∞', latex: '\\infty', title: 'infini' },
      { id: 'deriv', label: 'd/dx', latex: '\\frac{d}{dx}#?', title: 'dérivée' },
      { id: 'partial-deriv', label: '∂/∂x', latex: '\\frac{\\partial}{\\partial x}#?', title: 'dérivée partielle' },
    ],
  },
  {
    id: 'greek',
    name: 'Grec',
    buttons: [
      { id: 'alpha', label: 'α', latex: '\\alpha' },
      { id: 'beta', label: 'β', latex: '\\beta' },
      { id: 'gamma', label: 'γ', latex: '\\gamma' },
      { id: 'delta', label: 'δ', latex: '\\delta' },
      { id: 'epsilon', label: 'ε', latex: '\\epsilon' },
      { id: 'theta', label: 'θ', latex: '\\theta' },
      { id: 'lambda', label: 'λ', latex: '\\lambda' },
      { id: 'mu', label: 'μ', latex: '\\mu' },
      { id: 'pi', label: 'π', latex: '\\pi' },
      { id: 'sigma', label: 'σ', latex: '\\sigma' },
      { id: 'phi', label: 'φ', latex: '\\phi' },
      { id: 'omega', label: 'ω', latex: '\\omega' },
      { id: 'Gamma', label: 'Γ', latex: '\\Gamma' },
      { id: 'Delta', label: 'Δ', latex: '\\Delta' },
      { id: 'Sigma', label: 'Σ', latex: '\\Sigma' },
      { id: 'Pi', label: 'Π', latex: '\\Pi' },
      { id: 'Phi', label: 'Φ', latex: '\\Phi' },
      { id: 'Omega', label: 'Ω', latex: '\\Omega' },
    ],
  },
  {
    id: 'advanced',
    name: 'Avancé',
    buttons: [
      { id: 'gamma-fn', label: 'Γ(z)', latex: '\\Gamma(#?)', title: 'fonction gamma' },
      { id: 'zeta', label: 'ζ(s)', latex: '\\zeta(#?)', title: 'fonction zêta de Riemann' },
      { id: 'eta', label: 'η(s)', latex: '\\operatorname{\\eta}(#?)', title: 'fonction eta de Dirichlet' },
      { id: 'beta-fn', label: 'β(s)', latex: '\\operatorname{\\beta}(#?)', title: 'fonction beta de Dirichlet' },
      { id: 'polylog', label: 'Liₙ(z)', latex: '\\operatorname{Li}_{#?}(#?)', title: 'polylogarithme' },
      { id: 'dilog', label: 'Li₂(z)', latex: '\\operatorname{Li}_{2}(#?)', title: 'dilogarithme' },
      { id: 'lambertw', label: 'W(z)', latex: '\\operatorname{W}(#?)', title: 'fonction W de Lambert' },
      { id: 'erf', label: 'erf', latex: '\\operatorname{erf}(#?)', title: 'fonction erreur' },
      { id: 'erfc', label: 'erfc', latex: '\\operatorname{erfc}(#?)', title: 'fonction erreur complémentaire' },
      { id: 'beta2', label: 'B(x,y)', latex: '\\operatorname{B}(#?,#?)', title: 'fonction bêta' },
      { id: 'hyper2f1', label: '₂F₁', latex: '\\,{}_2F_1\\left(#?;#?;#?\\right)', title: 'hypergéométrique' },
      { id: 'meijer-g', label: 'Meijer G', latex: '\\operatorname{G}^{#?}_{#?}\\left(#?\\right)', title: 'fonction de Meijer' },
      { id: 'pochhammer', label: '(a)ₙ', latex: '\\left(#?\\right)_{#?}', title: 'symbole de Pochhammer' },
      { id: 'exp-integral-ei', label: 'Ei', latex: '\\operatorname{Ei}(#?)', title: 'exponentielle intégrale' },
      { id: 'cos-integral-ci', label: 'Ci', latex: '\\operatorname{Ci}(#?)', title: 'cosinus intégral' },
      { id: 'sin-integral-si', label: 'Si', latex: '\\operatorname{Si}(#?)', title: 'sinus intégral' },
      { id: 'sinh-integral-shi', label: 'Shi', latex: '\\operatorname{Shi}(#?)', title: 'sinus hyperbolique intégral' },
      { id: 'cosh-integral-chi', label: 'Chi', latex: '\\operatorname{Chi}(#?)', title: 'cosinus hyperbolique intégral' },
      { id: 'barnes-g', label: 'G', latex: '\\operatorname{G}(#?)', title: 'fonction G de Barnes' },
      { id: 'struve-h', label: 'Hᵥ', latex: '\\operatorname{H}_{#?}(#?)', title: 'fonction de Struve' },
      { id: 'bickley-ki', label: 'Kiᵥ', latex: '\\operatorname{Ki}_{#?}(#?)', title: 'fonction de Bickley' },
      { id: 'parabolic-c', label: 'C', latex: '\\operatorname{C}(#?)', title: 'fonction de Fresnel C' },
      { id: 'parabolic-s', label: 'S', latex: '\\operatorname{S}(#?)', title: 'fonction de Fresnel S' },
    ],
  },
  {
    id: 'special',
    name: 'Spécial',
    buttons: [
      { id: 'airy-ai', label: 'Ai', latex: '\\operatorname{Ai}(#?)', title: 'fonction d\'Airy Ai' },
      { id: 'airy-bi', label: 'Bi', latex: '\\operatorname{Bi}(#?)', title: 'fonction d\'Airy Bi' },
      { id: 'bessel-j', label: 'Jᵥ', latex: '\\operatorname{J}_{#?}(#?)', title: 'fonction de Bessel J' },
      { id: 'bessel-y', label: 'Yᵥ', latex: '\\operatorname{Y}_{#?}(#?)', title: 'fonction de Bessel Y' },
      { id: 'bessel-i', label: 'Iᵥ', latex: '\\operatorname{I}_{#?}(#?)', title: 'fonction de Bessel modifiée I' },
      { id: 'bessel-k', label: 'Kᵥ', latex: '\\operatorname{K}_{#?}(#?)', title: 'fonction de Bessel modifiée K' },
      { id: 'hankel-1', label: 'Hᵥ⁽¹⁾', latex: '\\operatorname{H}^{(1)}_{#?}(#?)', title: 'fonction de Hankel de première espèce' },
      { id: 'hankel-2', label: 'Hᵥ⁽²⁾', latex: '\\operatorname{H}^{(2)}_{#?}(#?)', title: 'fonction de Hankel de seconde espèce' },
      { id: 'digamma', label: 'ψ', latex: '\\psi(#?)', title: 'fonction digamma' },
      { id: 'polygamma', label: 'ψ⁽ᵐ⁾', latex: '\\psi^{(#?)}(#?)', title: 'fonction polygamma' },
      { id: 'exp-integral-e1', label: 'E₁', latex: '\\operatorname{E}_{1}(#?)', title: 'exponentielle intégrale E1' },
      { id: 'log-integral-li', label: 'li', latex: '\\operatorname{li}(#?)', title: 'logarithme intégral' },
      { id: 'fresnel-c', label: 'Fresnel C', latex: '\\operatorname{C}(#?)', title: 'fonction de Fresnel C' },
      { id: 'fresnel-s', label: 'Fresnel S', latex: '\\operatorname{S}(#?)', title: 'fonction de Fresnel S' },
    ],
  },
  {
    id: 'special-plus',
    name: 'Spécial +',
    buttons: [
      { id: 'tan-integral-ti', label: 'Tiₙ(z)', latex: '\\operatorname{Ti}_{#?}(#?)', title: 'intégrale tangente généralisée (Tiₙ)' },
      { id: 'anger', label: 'Jᵥ(z)', latex: '\\mathbf{J}_{#?}(#?)', title: 'fonction d\'Anger' },
      { id: 'kelvin-ber', label: 'berₙ(z)', latex: '\\operatorname{ber}_{#?}(#?)', title: 'fonction de Kelvin ber' },
      { id: 'kelvin-bei', label: 'beiₙ(z)', latex: '\\operatorname{bei}_{#?}(#?)', title: 'fonction de Kelvin bei' },
      { id: 'sinc', label: 'sinc', latex: '\\operatorname{sinc}(#?)', title: 'sinus cardinal' },
      { id: 'tanc', label: 'tanc', latex: '\\operatorname{tanc}(#?)', title: 'tangente cardinal' },
      { id: 'sinhc', label: 'sinhc', latex: '\\operatorname{sinhc}(#?)', title: 'sinus hyperbolique cardinal' },
      { id: 'jinc', label: 'jinc', latex: '\\operatorname{jinc}(#?)', title: 'fonction de Bessinc (jinc)' },
      { id: 'xi-riemann', label: 'ξ(s)', latex: '\\xi(#?)', title: 'fonction xi de Riemann' },
      { id: 'q-gamma', label: 'Γ_q(z)', latex: '\\Gamma_{#?}(#?)', title: 'q-fonction gamma' },
      { id: 'q-beta', label: 'B_q(x,y)', latex: '\\operatorname{B}_{#?}(#?,#?)', title: 'q-fonction bêta' },
      { id: 'q-pochhammer', label: '(a;q)ₙ', latex: '\\left(#?;#?\\right)_{#?}', title: 'symbole q-Pochhammer' },
      { id: 'q-hypergeom', label: 'ᵣφₛ', latex: '\\,{}_r\\phi_s\\left(#?;#?;#?\\right)', title: 'série q-hypergéométrique basique' },
      { id: 'exp-integral-en', label: 'Eₙ(z)', latex: '\\operatorname{E}_{#?}(#?)', title: 'exponentielle intégrale généralisée Eₙ' },
      { id: 'beta-inc', label: 'B_z(a,b)', latex: '\\operatorname{B}_{#?}(#?,#?)', title: 'fonction bêta incomplète' },
      { id: 'gamma-inc-lower', label: 'γ(s,x)', latex: '\\gamma(#?,#?)', title: 'gamma incomplète inférieure' },
      { id: 'gamma-inc-upper', label: 'Γ(s,x)', latex: '\\Gamma(#?,#?)', title: 'gamma incomplète supérieure' },
      { id: 'clausen', label: 'Clₙ(z)', latex: '\\operatorname{Cl}_{#?}(#?)', title: 'fonction de Clausen' },
      { id: 'legendre-chi', label: 'χᵥ(z)', latex: '\\operatorname{\\chi}_{#?}(#?)', title: 'fonction chi de Legendre' },
      { id: 'lobachevsky', label: 'L(x)', latex: '\\operatorname{L}(#?)', title: 'fonction de Lobachevsky' },
      { id: 'beta-exp', label: 'BEF(x)', latex: '\\operatorname{BEF}(#?,#?,#?)', title: 'fonction exponentielle bêta' },
      { id: 'alpha-fn', label: 'α(x)', latex: '\\operatorname{\\alpha}(#?)', title: 'fonction alpha' },
      { id: 'hurwitz-zeta', label: 'ζ(s,a)', latex: '\\zeta(#?,#?)', title: 'fonction zêta de Hurwitz' },
    ],
  },
  {
    id: 'set-logic',
    name: 'Ensembles / Logique',
    buttons: [
      { id: 'bigcup', label: '⋃', latex: '\\bigcup_{k=#?}^{#?} #?', title: 'union' },
      { id: 'bigcap', label: '⋂', latex: '\\bigcap_{k=#?}^{#?} #?', title: 'intersection' },
      { id: 'bigvee', label: '⋁', latex: '\\bigvee_{k=#?}^{#?} #?', title: 'disjonction' },
      { id: 'bigwedge', label: '⋀', latex: '\\bigwedge_{k=#?}^{#?} #?', title: 'conjonction' },
      { id: 'bigoplus', label: '⊕', latex: '\\bigoplus_{k=#?}^{#?} #?', title: 'somme directe' },
      { id: 'bigotimes', label: '⊗', latex: '\\bigotimes_{k=#?}^{#?} #?', title: 'produit tensoriel' },
      { id: 'bigsqcup', label: '⊔', latex: '\\bigsqcup_{k=#?}^{#?} #?', title: 'union disjointe' },
      { id: 'biguplus', label: '⊎', latex: '\\biguplus_{k=#?}^{#?} #?', title: 'union disjointe (uplus)' },
      { id: 'subset', label: '⊂', latex: '\\subset', title: 'inclusion stricte' },
      { id: 'supset', label: '⊃', latex: '\\supset', title: 'contient strictement' },
      { id: 'subseteq', label: '⊆', latex: '\\subseteq', title: 'inclusion' },
      { id: 'supseteq', label: '⊇', latex: '\\supseteq', title: 'contient' },
      { id: 'in', label: '∈', latex: '\\in', title: 'appartient à' },
      { id: 'notin', label: '∉', latex: '\\notin', title: 'n\'appartient pas à' },
      { id: 'forall', label: '∀', latex: '\\forall', title: 'pour tout' },
      { id: 'exists', label: '∃', latex: '\\exists', title: 'il existe' },
    ],
  },
  {
    id: 'hypergeometric',
    name: 'Hypergéométrique',
    buttons: [
      { id: 'hyper-0f1', label: '₀F₁', latex: '\\,{}_0F_1\\left(;#?;#?\\right)', title: 'hypergéométrique confluente' },
      { id: 'hyper-1f1', label: '₁F₁', latex: '\\,{}_1F_1\\left(#?;#?;#?\\right)', title: 'fonction de Kummer' },
      { id: 'hyper-2f1', label: '₂F₁', latex: '\\,{}_2F_1\\left(#?;#?;#?\\right)', title: 'hypergéométrique gaussienne' },
      { id: 'hyper-pfq', label: 'ₚF_q', latex: '\\,{}_pF_q\\left(#?;#?;#?\\right)', title: 'hypergéométrique généralisée' },
      { id: 'tricomi-u', label: 'U', latex: '\\operatorname{U}(#?,#?,#?)', title: 'fonction de Tricomi' },
      { id: 'whittaker-m', label: 'M', latex: '\\operatorname{M}_{#?,#?}(#?)', title: 'fonction de Whittaker M' },
      { id: 'whittaker-w', label: 'W', latex: '\\operatorname{W}_{#?,#?}(#?)', title: 'fonction de Whittaker W' },
    ],
  },
  {
    id: 'elliptic',
    name: 'Elliptique',
    buttons: [
      { id: 'elliptic-k', label: 'K(k)', latex: '\\operatorname{K}(#?)', title: 'intégrale elliptique complète de première espèce' },
      { id: 'elliptic-e', label: 'E(k)', latex: '\\operatorname{E}(#?)', title: 'intégrale elliptique complète de seconde espèce' },
      { id: 'elliptic-pi', label: 'Π', latex: '\\operatorname{\\Pi}(#?;#?)', title: 'intégrale elliptique complète de troisième espèce' },
      { id: 'jacobi-sn', label: 'sn', latex: '\\operatorname{sn}(#?,#?)', title: 'sn de Jacobi' },
      { id: 'jacobi-cn', label: 'cn', latex: '\\operatorname{cn}(#?,#?)', title: 'cn de Jacobi' },
      { id: 'jacobi-dn', label: 'dn', latex: '\\operatorname{dn}(#?,#?)', title: 'dn de Jacobi' },
      { id: 'weierstrass-p', label: '℘', latex: '\\wp(#?;#?)', title: 'fonction de Weierstrass' },
    ],
  },
  {
    id: 'orthogonal',
    name: 'Orthogonal',
    buttons: [
      { id: 'legendre-p', label: 'Pₙ', latex: '\\operatorname{P}_{#?}(#?)', title: 'polynôme de Legendre' },
      { id: 'chebyshev-t', label: 'Tₙ', latex: '\\operatorname{T}_{#?}(#?)', title: 'polynôme de Tchebychev de première espèce' },
      { id: 'chebyshev-u', label: 'Uₙ', latex: '\\operatorname{U}_{#?}(#?)', title: 'polynôme de Tchebychev de seconde espèce' },
      { id: 'laguerre-l', label: 'Lₙ', latex: '\\operatorname{L}_{#?}(#?)', title: 'polynôme de Laguerre' },
      { id: 'hermite-h', label: 'Hₙ', latex: '\\operatorname{H}_{#?}(#?)', title: 'polynôme d\'Hermite' },
      { id: 'spherical-y', label: 'Yₗᵐ', latex: '\\operatorname{Y}_{#?}^{#?}(#?)', title: 'harmonique sphérique' },
    ],
  },
  {
    id: 'combinatorics',
    name: 'Nombres / Combinatoire',
    buttons: [
      { id: 'euler-gamma', label: 'γ', latex: '\\gamma', title: 'constante d\'Euler-Mascheroni' },
      { id: 'factorial', label: 'n!', latex: '#?!', title: 'factorielle' },
      { id: 'binomial', label: 'C(n,k)', latex: '\\binom{#?}{#?}', title: 'coefficient binomial' },
      { id: 'gcd', label: 'gcd', latex: '\\operatorname{gcd}(#?,#?)', title: 'plus grand commun diviseur' },
      { id: 'lcm', label: 'ppcm', latex: '\\operatorname{lcm}(#?,#?)', title: 'plus petit commun multiple' },
      { id: 'bernoulli-b', label: 'Bₙ', latex: '\\operatorname{B}_{#?}', title: 'nombre de Bernoulli' },
      { id: 'euler-e', label: 'Eₙ', latex: '\\operatorname{E}_{#?}', title: 'nombre d\'Euler' },
    ],
  },
  {
    id: 'constants',
    name: 'Constantes',
    buttons: [
      { id: 'const-e', label: 'e', latex: 'e', title: 'nombre d\'Euler' },
      { id: 'const-pi', label: 'π', latex: '\\pi', title: 'pi' },
      { id: 'const-i', label: 'i', latex: 'i', title: 'unité imaginaire' },
      { id: 'const-golden', label: 'φ', latex: '\\varphi', title: 'nombre d\'or' },
      { id: 'const-silver', label: 'δ_S', latex: '\\delta_{S}', title: 'nombre d\'argent' },
      { id: 'const-catalan', label: 'K (Catalan)', latex: '\\operatorname{K}', title: 'constante de Catalan' },
      { id: 'const-khinchin', label: 'K (Khintchine)', latex: '\\operatorname{K}', title: 'constante de Khintchine' },
      { id: 'const-gieseking', label: 'G (Gieseking)', latex: '\\operatorname{G}', title: 'constante de Gieseking' },
      { id: 'const-gauss', label: 'G (Gauss)', latex: '\\operatorname{G}', title: 'constante de Gauss' },
      { id: 'const-gompertz', label: 'G (Gompertz)', latex: '\\operatorname{G}', title: 'constante de Gompertz' },
      { id: 'const-glaisher', label: 'A', latex: '\\operatorname{A}', title: 'constante de Glaisher-Kinkelin' },
      { id: 'const-lemniscate', label: 'ϖ', latex: '\\varpi', title: 'constante du lemniscate' },
      { id: 'const-omega', label: 'Ω', latex: '\\Omega', title: 'constante oméga' },
      { id: 'const-omega-2', label: 'ω₂', latex: '\\omega_{2}', title: 'constante oméga-2' },
      { id: 'const-soldner', label: 'µ', latex: '\\mu', title: 'constante de Soldner' },
      { id: 'const-feigenbaum', label: 'δ (Feigenbaum)', latex: '\\delta', title: 'constante de Feigenbaum' },
      { id: 'const-gompertz-delta', label: 'δ (Gompertz)', latex: '\\delta', title: 'constante de Gompertz' },
      { id: 'const-golomb', label: 'λ', latex: '\\lambda', title: 'constante de Golomb-Dickman' },
      { id: 'const-apery', label: 'ζ(3)', latex: '\\zeta(3)', title: 'constante d\'Apéry' },
      { id: 'const-meissel', label: 'M₁', latex: '\\operatorname{M}_{1}', title: 'constante de Meissel-Mertens' },
      { id: 'const-brun', label: 'B₂', latex: '\\operatorname{B}_{2}', title: 'constante de Brun' },
      { id: 'const-twin', label: 'C₂', latex: '\\operatorname{C}_{2}', title: 'constante des nombres premiers jumeaux' },
      { id: 'const-plastic', label: 'ρ', latex: '\\rho', title: 'nombre plastique' },
      { id: 'const-cahen', label: 'C', latex: '\\operatorname{C}', title: 'constante de Cahen' },
    ],
  },
];


export interface MathMenuAction {
  id: string;
  label: string;
  latex: string;
  allowedButtonIds?: string[];
}

export const MENU_ACTIONS: MathMenuAction[] = [
  { id: 'matrix-2x2', label: 'Matrice 2×2', latex: '\\begin{pmatrix} #? & #? \\\\ #? & #? \\end{pmatrix}' },
  { id: 'matrix-3x3', label: 'Matrice 3×3', latex: '\\begin{pmatrix} #? & #? & #? \\\\ #? & #? & #? \\\\ #? & #? & #? \\end{pmatrix}' },
  { id: 'det-2x2', label: 'Déterminant 2×2', latex: '\\begin{vmatrix} #? & #? \\\\ #? & #? \\end{vmatrix}' },
  { id: 'system-2', label: 'Système 2 équations', latex: '\\begin{cases} #? = #? \\\\ #? = #? \\end{cases}' },
  { id: 'system-3', label: 'Système 3 équations', latex: '\\begin{cases} #? = #? \\\\ #? = #? \\\\ #? = #? \\end{cases}' },
  { id: 'fraction', label: 'Fraction', latex: '\\frac{#?}{#?}' },
  { id: 'sqrt', label: 'Racine carrée', latex: '\\sqrt{#?}' },
  { id: 'nth-root', label: 'Racine n-ième', latex: '\\sqrt[#?]{#?}' },
  { id: 'power', label: 'Puissance', latex: '#?^{#?}' },
  { id: 'menu-power-n', label: 'Puissance n', latex: '#?^{n}' },
  { id: 'sum', label: 'Somme', latex: '\\sum_{k=#?}^{#?} #?' },
  { id: 'prod', label: 'Produit', latex: '\\prod_{k=#?}^{#?} #?' },
  { id: 'menu-log-base', label: 'Logarithme base a', latex: '\\log_{#?}(#?)' },
  { id: 'integral', label: 'Intégrale', latex: '\\int_{#?}^{#?} #? \\,dx' },
  { id: 'limit', label: 'Limite', latex: '\\lim_{#? \\to #?} #?' },
  { id: 'derivative', label: 'Dérivée', latex: '\\frac{d}{dx}#?' },
  { id: 'partial', label: 'Dérivée partielle', latex: '\\frac{\\partial}{\\partial x}#?' },
  { id: 'overline', label: 'Conjugué / barre', latex: '\\overline{#?}' },
  { id: 'hat', label: 'Chapeau', latex: '\\hat{#?}' },
  { id: 'vec', label: 'Vecteur', latex: '\\vec{#?}' },
];
